version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ../ssldata/certbot/conf:/etc/letsencrypt
      - ../ssldata/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ../ssldata/certbot/conf:/etc/letsencrypt
      - ../ssldata/certbot/www:/var/www/certbot